from arcade import load_texture
from pathlib import Path

# plains_sprite = load_texture(Path('Sprites') / 'Plains_Tile_0.png')
# character = load_texture(Path('Sprites') / 'Knight_Sprite_0_Start_2_Foot.png')
# character_flipped = load_texture(Path('Sprites') / 'Knight_Sprite_0_Start_2_Foot_Flipped.png')
# enemy_head = load_texture(Path('Sprites') / 'Knight_Sprite_Head.png')
# enemy_head_flipped = load_texture(Path('Sprites') / 'Knight_Sprite_Head_Flipped.png')
# swamp_monster = load_texture(Path('Sprites') / 'Swamp_Monster_0.png')
# knife = load_texture(Path('Sprites') / 'Rusty_Knife_1.png')
# x = load_texture(Path('Sprites') / 'X.png')
blank_button_dark = load_texture(Path('Sprites') / 'Button_Square_(No Decor)_0Dark.png')
blank_button_light = load_texture(Path('Sprites') / 'Button_Square_(No Decor)_1Light.png')
blank_button_light_middle = load_texture(Path('Sprites') / 'Button_Square_(No Decor)_2LightMiddle.png')
red_disc = load_texture(Path('Sprites') / 'Disc_Red.png')
yellow_disc = load_texture(Path('Sprites') / 'Disc_Yellow.png')
blue_disc = load_texture(Path('Sprites') / 'Disc_Blue.png')
green_disc = load_texture(Path('Sprites') / 'Disc_Green.png')
lime_disc = load_texture(Path('Sprites') / 'Disc_Lime.png')
orange_disc = load_texture(Path('Sprites') / 'Disc_Orange.png')
pink_disc = load_texture(Path('Sprites') / 'Disc_Pink.png')
purple_disc = load_texture(Path('Sprites') / 'Disc_Purple.png')
disc_slot = load_texture(Path('Sprites') / 'Disk_Slot.png')
mag_glass_dark = load_texture(Path('Sprites') / 'MagGlassDark.png')
mag_glass_light = load_texture(Path('Sprites') / 'MagGlassLight.png')
x = load_texture(Path('Sprites') / 'X.png')
